### ISSUE TITLE
some enhancment

### ISSUE THREAD

**Issue by devmondo** [Flux159/uhttp#1]
really great work and API, thanks a lot for this library.

i have some suggestions if you could please take into account
- make transformers accept arrays of functions, this way we can add and remove multiple ones instead of having one function , similar to angular interceptors and axios 
  -add baseurl, this is very helpful to stop repeating typing urls all the time
  -ability to show progress bar

thanks in advanced.

**Comment by Flux159** [comment]
Hi, thanks for the suggestions!

About the enhancements:
- ability to show progress bar: This exists for uploads, but doesn't exist for downloads - I know where to add this for uhttp client side (lines 446 & 494 as of v1.2.3). Definitely an improvement to add (referencing this document on XHR download progress events: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress ). I'll take a look into this (it will probably be an option called "downloadProgressHandler" in a future version - I think it may take a bit more research into how to do this for the server side uhttp).
- add baseurl: For requests to the same base endpoint, I organize my uhttp ajax calls into a service object (very similar to angular's services), and simply store the base endpoint as a variable in that service. Here's an example (personally I use browserify script to help organize my code & combine all my scripts into a single client-side js file - browserify supports commonjs require & module.exports), you're free to use any dependency management system you want though:

``` javascript
var uhttp = require('uhttp');

var baseUrl = 'http://my.example.endpoint.com';

var User = {
  login: function(user) {
    return uhttp.post(baseUrl + '/login', user);
  },
  register: function(user) {
    return uhttp.post(baseUrl + '/register', user);
  }
};

module.exports = User;
```

You would use it as follows (in a controller, etc):

``` javascript
var User = require('../services/User');

User.login({username: 'example', password: 'donthardcodepasswords'}).then(function(res) {
//...
}).catch(function(err) {
//...
});

```

EDIT: Alternatively, you could put all your hardcoded endpoints into a "config" module and load them from there (so instead of coding your endpoints into the service itself, just do "var config = require('../config')" and use it from there) - this also allows you to change the config file from dev to test to prod easily by defining different config files and using a build script to change between them.
- make transformers accept arrays for functions: I know that angular does this - but I'm struggling to find a good reason for adding this. First I'm not too much of a fan of interceptors at all - I only added them because they're useful for setting once or twice - either per request or globally (example is using formdata instead of json or globally setting some authentication headers). The entire idea of multiple interceptors seems flawed - if you think about an ajax function as simply a function y = f(x), an interceptor is doing y = g(f(x)); multiple interceptors is essentially y = h(g(f(x)))... ; using a combination of interceptors seems like an easy way to lose understanding of your codebase. There's probably also a better way to structure your code to not use multiple interceptors. I'll give this some thought, but I would need someone to provide a concrete example of why this is needed and why its a good idea.

**Comment by devmondo** [comment]
hi, 
thanks a lot for the detailed reply man, well put :)

regarding progress, i mean something like jquery's ajaxstart and ajaxstop, if uhttp can fire events similar to this  we can show loading image for any ajax request.

regarding baseurl, yes i do similar concept of config file, well i used your request interceptor to append global api url to the request's url , hence why i like interceptors :) 

funny enough i picked your lib because of 2 things, clean api, and interceptors :) 

we may disagree on them being flawed or not, but they help a lot, for me they are the same concept as middleware in expressjs or actionfilters in asp.net mvc.

why i think we should have them as an array, it is because you can add and remove functionalities based on requirement, plus the whole purpose is to define things once and apply it on each request as you said.

what i also loved is you have interceptor for data and interceptor for operation itself, this is really cool !

thanks again for the detailed support  :)

**Comment by Flux159** [comment]
So I added Issue #2 for start, progress, stop indicators - I don't have time immediately to get to them, but I'll add them when I get some time to look through whether nodejs has similar events and to write the code/tests. This will be new functionality so it will probably be in v1.3.0.

About baseurl: Adding this is essentially adding global state to uhttp if you use it as a global option. This may not be an issue for your use case, but overall this is a bad idea - particularly when using uhttp server side where you definitely want to avoid any global state using uhttp (speaking from experience). I'm going to avoid adding this unless there's a lot more demand for this in particular - there are also other better alternatives to this that work and also avoid global state in uhttp.

Finally, multiple interceptors: While I do like express middleware - I've never had the use case where I want to add and/or remove middleware dynamically based on a specific route (I define all my middleware upfront and every route for that microservice executes the middleware - things like authentication can be specified with a prefix like '/auth/' so that all routes with /auth/ will run the auth middleware - no need to add/remove middleware dynamically while the service is running). Back to multiple interceptors - The idea of _adding and removing_ **interceptor** functionality based on requirement smells like a design flaw. Interceptors shouldn't really be handling your business logic, that's what the then/catch callbacks already provide you. We can discuss this further if you want, but at the moment I'm leaning towards leaving multiple interceptors out of uhttp (although they could always be added in a fork/branch).

**Comment by devmondo** [comment]
thank man for the detailed response, and suggestions :)

i do agree on most of what you said, but sometimes there are those cases :) 

regarding interceptors, yep, i experimented with chaining array of functions and it works 

and i love how we can set interceptors on global and per request .

at the end of the day, there is always more than way to do it, what is essential is to have a good api like what you provided, so we can have flexibility.

right now i think most pressing issue is the progress event, i hope it gets there soon 

thanks again for your understanding and ideas :)

**Comment by Flux159** [comment]
Going to close this issue since its a few years old and V2.0 was just released.
